package com.nova.ai;

import android.os.Handler;
import android.os.Looper;
import org.json.JSONArray;
import org.json.JSONObject;
import java.io.BufferedReader;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.net.HttpURLConnection;
import java.net.URL;
import java.nio.charset.StandardCharsets;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

/** OpenAI-compatible provider using Responses API by default, with Chat Completions fallback and multimodal input. */
public final class NovaOpenAiCompatibleProvider implements NovaAiProvider {
    private final String endpoint; private final String apiKey; private final String model;
    private final ExecutorService executor=Executors.newSingleThreadExecutor(); private final Handler main=new Handler(Looper.getMainLooper());
    public NovaOpenAiCompatibleProvider(String baseUrl,String apiKey,String model){String base=baseUrl==null?"":baseUrl.trim();if(base.endsWith("/"))base=base.substring(0,base.length()-1);endpoint=(base.endsWith("/chat/completions")||base.endsWith("/responses"))?base:base+"/responses";this.apiKey=apiKey==null?"":apiKey.trim();this.model=model==null?"":model.trim();}
    @Override public void complete(String systemContext,String userInput,JSONObject toolCatalog,Callback callback){if(endpoint.isEmpty()||apiKey.isEmpty()||model.isEmpty()){postError(callback,new IllegalStateException("AI provider is not configured"));return;}executor.execute(()->{HttpURLConnection connection=null;try{boolean responses=endpoint.endsWith("/responses");JSONObject body=responses?buildResponsesBody(systemContext,userInput,toolCatalog):buildChatBody(systemContext,userInput,toolCatalog);connection=(HttpURLConnection)new URL(endpoint).openConnection();connection.setRequestMethod("POST");connection.setConnectTimeout(15000);connection.setReadTimeout(60000);connection.setDoOutput(true);connection.setRequestProperty("Content-Type","application/json");connection.setRequestProperty("Authorization","Bearer "+apiKey);try(OutputStream out=connection.getOutputStream()){out.write(body.toString().getBytes(StandardCharsets.UTF_8));}int code=connection.getResponseCode();InputStream stream=code>=200&&code<300?connection.getInputStream():connection.getErrorStream();String response=read(stream);if(code<200||code>=300)throw new IllegalStateException("AI HTTP "+code+": "+response);JSONObject parsed=new JSONObject(response);main.post(()->{if(callback!=null)callback.onSuccess(parsed);});}catch(Exception error){postError(callback,error);}finally{if(connection!=null)connection.disconnect();}});}
    private JSONObject buildResponsesBody(String system,String input,JSONObject catalog)throws Exception{JSONObject body=new JSONObject().put("model",model).put("instructions",system==null?"":system).put("input",buildResponsesInput(catalog,input)).put("tool_choice","auto");JSONArray tools=toResponsesTools(catalog==null?null:catalog.optJSONArray("tools"));if(tools.length()>0)body.put("tools",tools);return body;}
    private static JSONArray buildResponsesInput(JSONObject catalog,String latestInput)throws Exception{JSONArray input=new JSONArray();JSONArray context=catalog==null?null:catalog.optJSONArray("context");if(context!=null)for(int i=0;i<context.length();i++){JSONObject item=context.optJSONObject(i);if(item==null)continue;String role=item.optString("role","user");if("tool".equals(role)){String output=item.optString("content","");String callId=item.optString("tool_call_id","");if(!callId.isEmpty())input.put(new JSONObject().put("type","function_call_output").put("call_id",callId).put("output",output));String image=item.optString("vision_image","");if(!image.isEmpty()){String mime=item.optString("vision_mime","image/jpeg");JSONArray content=new JSONArray().put(new JSONObject().put("type","input_text").put("text","Inspect this fresh screenshot together with the tool result above.")).put(new JSONObject().put("type","input_image").put("image_url","data:"+mime+";base64,"+image));input.put(new JSONObject().put("role","user").put("content",content));}}else if("assistant".equals(role)&&item.has("tool_calls")){JSONArray calls=item.optJSONArray("tool_calls");if(calls!=null)for(int j=0;j<calls.length();j++){JSONObject call=calls.optJSONObject(j);if(call==null)continue;JSONObject fn=call.optJSONObject("function");if(fn==null)continue;input.put(new JSONObject().put("type","function_call").put("call_id",call.optString("id","")).put("name",fn.optString("name","")).put("arguments",fn.optString("arguments","{}")));}String content=item.optString("content","");if(!content.isEmpty())input.put(new JSONObject().put("role","assistant").put("content",content));}else{Object content=item.opt("content");input.put(new JSONObject().put("role",role).put("content",content instanceof JSONArray?content:item.optString("content","")));}}if(latestInput!=null&&!latestInput.trim().isEmpty())input.put(new JSONObject().put("role","user").put("content",latestInput));return input;}
    private JSONObject buildChatBody(String system,String input,JSONObject catalog)throws Exception{return new JSONObject().put("model",model).put("messages",buildChatMessages(system,input,catalog)).put("temperature",0.2).put("tool_choice","auto").put("tools",toChatTools(catalog==null?null:catalog.optJSONArray("tools")));}
    private static JSONArray buildChatMessages(String system,String input,JSONObject catalog)throws Exception{JSONArray messages=new JSONArray().put(new JSONObject().put("role","system").put("content",system==null?"":system));JSONArray context=catalog==null?null:catalog.optJSONArray("context");if(context!=null)for(int i=0;i<context.length();i++){JSONObject item=context.optJSONObject(i);if(item==null)continue;Object content=item.opt("content");JSONObject msg=new JSONObject().put("role",item.optString("role","user")).put("content",content instanceof JSONArray?content:item.optString("content",""));if(item.has("tool_call_id"))msg.put("tool_call_id",item.optString("tool_call_id"));if(item.has("name"))msg.put("name",item.optString("name"));if(item.has("tool_calls"))msg.put("tool_calls",item.optJSONArray("tool_calls"));messages.put(msg);}if(input!=null&&!input.trim().isEmpty())messages.put(new JSONObject().put("role","user").put("content",input));return messages;}
    private static JSONArray toResponsesTools(JSONArray catalog)throws Exception{JSONArray result=new JSONArray();if(catalog==null)return result;for(int i=0;i<catalog.length();i++){JSONObject item=catalog.optJSONObject(i);if(item==null)continue;String name=item.optString("id","");if(name.isEmpty())continue;JSONObject schema=item.optJSONObject("schema");if(schema==null)schema=new JSONObject().put("type","object");result.put(new JSONObject().put("type","function").put("name",name).put("description",item.optString("description","")).put("parameters",schema));}return result;}
    private static JSONArray toChatTools(JSONArray catalog)throws Exception{JSONArray result=new JSONArray();if(catalog==null)return result;for(int i=0;i<catalog.length();i++){JSONObject item=catalog.optJSONObject(i);if(item==null)continue;String name=item.optString("id","");if(name.isEmpty())continue;JSONObject schema=item.optJSONObject("schema");if(schema==null)schema=new JSONObject().put("type","object");result.put(new JSONObject().put("type","function").put("function",new JSONObject().put("name",name).put("description",item.optString("description","")).put("parameters",schema)));}return result;}
    private static String read(InputStream stream)throws Exception{if(stream==null)return"";StringBuilder result=new StringBuilder();try(BufferedReader reader=new BufferedReader(new InputStreamReader(stream,StandardCharsets.UTF_8))){String line;while((line=reader.readLine())!=null)result.append(line);}return result.toString();}
    private void postError(Callback callback,Exception error){if(callback!=null)main.post(()->callback.onError(error));}
}
