package com.nova.ai;

import android.content.Context;
import android.os.Build;
import android.os.PowerManager;
import org.json.JSONArray;
import org.json.JSONObject;
import java.io.BufferedReader;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URI;
import java.net.URL;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.TimeZone;

/** Cross-cutting NOVA tools: research, memory, preferences, notifications, device state and time. */
public final class NovaFeatureTools {
    private NovaFeatureTools() { }
    public static NovaTool memorySearch(Context c){return new NovaTool(){public String id(){return"memory.search";}public String description(){return"Search NOVA's persistent long-term memories by keywords.";}public JSONObject schema(){try{return new JSONObject().put("type","object").put("required",new JSONArray().put("query")).put("properties",new JSONObject().put("query",new JSONObject().put("type","string")).put("max_results",new JSONObject().put("type","integer")));}catch(Exception e){return new JSONObject();}}public JSONObject execute(JSONObject i){String q=i==null?"":i.optString("query","").trim();int m=Math.max(1,Math.min(10,i==null?5:i.optInt("max_results",5)));return new JSONObject().put("query",q).put("results",NovaRuntime.get(c).memoryManager().search(q,m));}};}
    public static NovaTool preference(Context c){return new NovaTool(){public String id(){return"preference.manage";}public String description(){return"Read or explicitly store non-sensitive user workflow preferences for personalization.";}public JSONObject schema(){try{return new JSONObject().put("type","object").put("properties",new JSONObject().put("action",new JSONObject().put("type","string")).put("key",new JSONObject().put("type","string")).put("value",new JSONObject().put("type","string")));}catch(Exception e){return new JSONObject();}}public JSONObject execute(JSONObject i){String a=i==null?"get":i.optString("action","get").toLowerCase();String k=i==null?"":i.optString("key","");NovaPreferenceEngine p=NovaRuntime.get(c).preferences();if("set".equals(a)){boolean ok=p.learn(k,i.optString("value",""));return new JSONObject().put("ok",ok);}if("forget".equals(a))return new JSONObject().put("ok",p.forget(k));if("snapshot".equals(a))return new JSONObject().put("preferences",p.snapshot());return new JSONObject().put("key",k).put("value",p.get(k));}};}
    public static NovaTool notifications(Context c){return new NovaTool(){public String id(){return"notification.recent";}public String description(){return"Return recent notification metadata captured by NOVA.";}public JSONObject schema(){return new JSONObject();}public JSONObject execute(JSONObject i){return new JSONObject().put("notifications",NovaNotificationStore.recent(c));}};}
    public static NovaTool devices(Context c){return new NovaTool(){public String id(){return"device.list";}public String description(){return"List NOVA nodes currently known to this device.";}public JSONObject schema(){return new JSONObject();}public JSONObject execute(JSONObject i){return new JSONObject().put("nodes",NovaRuntime.get(c).devices().list());}};}
    public static NovaTool time(Context c){return new NovaTool(){public String id(){return"system.time";}public String description(){return"Return the current device time, epoch milliseconds and timezone for scheduling.";}public JSONObject schema(){return new JSONObject();}public JSONObject execute(JSONObject i){long now=System.currentTimeMillis();return new JSONObject().put("epochMs",now).put("iso",new java.text.SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ssXXX",java.util.Locale.ROOT).format(new java.util.Date(now))).put("timezone",TimeZone.getDefault().getID());}};}
    public static NovaTool research(Context c){return new NovaTool(){
        public String id(){return"web.research";}public String description(){return"Run a bounded multi-source web research pass and return source material for synthesis.";}public JSONObject schema(){try{return new JSONObject().put("type","object").put("required",new JSONArray().put("query")).put("properties",new JSONObject().put("query",new JSONObject().put("type","string")).put("max_sources",new JSONObject().put("type","integer")));}catch(Exception e){return new JSONObject();}}
        public JSONObject execute(JSONObject i)throws Exception{String q=i==null?"":i.optString("query","").trim();if(q.isEmpty())throw new IllegalArgumentException("query_required");int max=Math.max(2,Math.min(5,i==null?4:i.optInt("max_sources",4)));JSONArray candidates=search(q),sources=new JSONArray();for(int n=0;n<candidates.length()&&sources.length()<max;n++){JSONObject x=candidates.optJSONObject(n);if(x==null)continue;String u=x.optString("url","");if(u.isEmpty())continue;try{JSONObject p=fetch(u);sources.put(new JSONObject().put("title",x.optString("title","")).put("url",u).put("snippet",x.optString("snippet","")).put("status",p.optInt("status",0)).put("text",NovaAgentPolicy.bounded(p.optString("text",""),5000)));}catch(Exception ignored){}}return new JSONObject().put("query",q).put("sources",sources).put("instruction","Synthesize the sources, distinguish facts from uncertainty, and mention source URLs in the final answer.");}
        private JSONArray search(String q)throws Exception{HttpURLConnection x=(HttpURLConnection)new URL("https://api.duckduckgo.com/?q="+URLEncoder.encode(q,"UTF-8")+"&format=json&no_html=1&no_redirect=1").openConnection();x.setConnectTimeout(8000);x.setReadTimeout(12000);x.setRequestProperty("User-Agent","NOVA-AI/1.0");int code=x.getResponseCode();String body=read(code>=200&&code<300?x.getInputStream():x.getErrorStream(),16000);x.disconnect();if(code<200||code>=300)throw new IllegalStateException("search_http_"+code);JSONObject d=new JSONObject(body);JSONArray r=new JSONArray();if(!d.optString("AbstractURL","").isEmpty())r.put(new JSONObject().put("title",d.optString("Heading","")).put("url",d.optString("AbstractURL","")).put("snippet",d.optString("AbstractText","")));add(d.optJSONArray("RelatedTopics"),r,8);return r;}
        private JSONObject fetch(String url)throws Exception{URI u=URI.create(url);if(u.getScheme()==null||!(u.getScheme().equalsIgnoreCase("http")||u.getScheme().equalsIgnoreCase("https"))||u.getHost()==null)throw new IllegalArgumentException("valid_http_url_required");HttpURLConnection x=(HttpURLConnection)new URL(url).openConnection();x.setConnectTimeout(8000);x.setReadTimeout(15000);x.setRequestProperty("User-Agent","NOVA-AI/1.0");int code=x.getResponseCode();String body=read(code>=200&&code<300?x.getInputStream():x.getErrorStream(),12000);x.disconnect();if(code<200||code>=300)throw new IllegalStateException("fetch_http_"+code);return new JSONObject().put("status",code).put("text",body.replaceAll("(?is)<script.*?>.*?</script>"," ").replaceAll("(?is)<style.*?>.*?</style>"," ").replaceAll("<[^>]+>"," ").replace("&nbsp;"," ").replace("&amp;","&").replaceAll("\\s+"," ").trim());}
        private void add(JSONArray a,JSONArray o,int m){if(a==null)return;for(int i=0;i<a.length()&&o.length()<m;i++){JSONObject x=a.optJSONObject(i);if(x==null)continue;if(x.has("Topics")){add(x.optJSONArray("Topics"),o,m);continue;}String u=x.optString("FirstURL","");if(!u.isEmpty())o.put(new JSONObject().put("title",x.optString("Text","")).put("url",u).put("snippet",x.optString("Text","")));}}
        private String read(InputStream s,int m)throws Exception{if(s==null)return"";StringBuilder b=new StringBuilder();try(BufferedReader r=new BufferedReader(new InputStreamReader(s,StandardCharsets.UTF_8))){String l;while((l=r.readLine())!=null&&b.length()<m)b.append(l).append('\n');}return b.substring(0,Math.min(m,b.length()));}
    };}
    public static NovaTool systemStatus(Context c){return new NovaTool(){public String id(){return"system.status";}public String description(){return"Return NOVA runtime, Android, provider, accessibility, node and interactive status.";}public JSONObject schema(){return new JSONObject();}public JSONObject execute(JSONObject i){PowerManager pm=(PowerManager)c.getSystemService(Context.POWER_SERVICE);return new JSONObject().put("android",Build.VERSION.SDK_INT).put("model",Build.MODEL).put("manufacturer",Build.MANUFACTURER).put("accessibility",NovaAccessibilityService.getInstance()!=null).put("provider",new NovaProviderConfig(c).isConfigured()).put("nodes",NovaRuntime.get(c).devices().list().length()).put("interactive",pm==null||pm.isInteractive());}};}
}
