package com.nova.ai;

import android.content.Context;
import android.graphics.Bitmap;
import android.os.Build;
import android.util.Base64;
import org.json.JSONArray;
import org.json.JSONObject;
import java.io.BufferedReader;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URLEncoder;
import java.net.URL;
import java.nio.charset.StandardCharsets;

/** Higher-level tools for web research, screen observation, scheduling and cross-device work. */
public final class NovaCapabilityTools {
    private NovaCapabilityTools() { }
    public static NovaTool webSearch(){return new NovaTool(){public String id(){return"web.search";}public String description(){return"Search the public web and return titles, URLs and snippets for research.";}public JSONObject schema(){try{return new JSONObject().put("type","object").put("required",new JSONArray().put("query")).put("properties",new JSONObject().put("query",new JSONObject().put("type","string")).put("max_results",new JSONObject().put("type","integer")));}catch(Exception e){return new JSONObject();}}public JSONObject execute(JSONObject input)throws Exception{String q=input==null?"":input.optString("query","").trim();if(q.isEmpty())throw new IllegalArgumentException("query_required");int max=Math.max(1,Math.min(8,input.optInt("max_results",5)));JSONObject d=getJson("https://api.duckduckgo.com/?q="+URLEncoder.encode(q,"UTF-8")+"&format=json&no_html=1&no_redirect=1");JSONArray r=new JSONArray();if(!d.optString("AbstractURL","").isEmpty())r.put(new JSONObject().put("title",d.optString("Heading","")).put("url",d.optString("AbstractURL","")).put("snippet",d.optString("AbstractText","")));addTopics(d.optJSONArray("RelatedTopics"),r,max);return new JSONObject().put("query",q).put("results",r).put("source","DuckDuckGo Instant Answer");}};}
    public static NovaTool webFetch(){return new NovaTool(){public String id(){return"web.fetch";}public String description(){return"Fetch a public HTTP/HTTPS page and return bounded readable text for research.";}public JSONObject schema(){try{return new JSONObject().put("type","object").put("required",new JSONArray().put("url")).put("properties",new JSONObject().put("url",new JSONObject().put("type","string")));}catch(Exception e){return new JSONObject();}}public JSONObject execute(JSONObject input)throws Exception{String url=input==null?"":input.optString("url","").trim();java.net.URI u=java.net.URI.create(url);if(u.getScheme()==null||!("http".equalsIgnoreCase(u.getScheme())||"https".equalsIgnoreCase(u.getScheme()))||u.getHost()==null)throw new IllegalArgumentException("valid_http_url_required");HttpURLConnection c=(HttpURLConnection)new URL(url).openConnection();c.setConnectTimeout(10000);c.setReadTimeout(20000);c.setRequestProperty("User-Agent","NOVA-AI/1.0");int code=c.getResponseCode();String body=read(code>=200&&code<300?c.getInputStream():c.getErrorStream(),12000);c.disconnect();if(code<200||code>=300)throw new IllegalStateException("web_http_"+code);return new JSONObject().put("url",url).put("status",code).put("text",stripHtml(body));}};}
    public static NovaTool screenObserve(Context context){return new NovaTool(){public String id(){return"screen.observe";}public String description(){return"Observe the active Android screen through accessibility plus fresh screenshot OCR and an optional screenshot image for multimodal models.";}public JSONObject schema(){try{return new JSONObject().put("type","object").put("properties",new JSONObject().put("query",new JSONObject().put("type","string")).put("include_image",new JSONObject().put("type","boolean")));}catch(Exception e){return new JSONObject();}}public JSONObject execute(JSONObject input)throws Exception{NovaAccessibilityService s=NovaAccessibilityService.getInstance();if(s==null)throw new IllegalStateException("accessibility_service_unavailable");String text=s.screenText(),ui=s.uiSnapshot(),q=input==null?"":input.optString("query","").trim();boolean imageRequested=input!=null&&input.optBoolean("include_image",true);JSONObject out=new JSONObject().put("text",NovaAgentPolicy.bounded(text,7000)).put("ui",NovaAgentPolicy.bounded(ui,9000));if(!q.isEmpty())out.put("contains",text.toLowerCase().contains(q.toLowerCase())||ui.toLowerCase().contains(q.toLowerCase()));if(Build.VERSION.SDK_INT>=30){out.put("visual_capture_available",true);Bitmap shot=s.captureScreen(1800);if(shot!=null){final Object lock=new Object();final String[] ocr={""};final boolean[] done={false};NovaOcrAnalyzer.recognize(shot,new NovaOcrAnalyzer.Callback(){public void onText(String v){synchronized(lock){ocr[0]=v;done[0]=true;lock.notifyAll();}}public void onError(Exception e){synchronized(lock){done[0]=true;lock.notifyAll();}}});synchronized(lock){if(!done[0])try{lock.wait(1800);}catch(InterruptedException e){Thread.currentThread().interrupt();}}out.put("screenshot_ocr",NovaAgentPolicy.bounded(ocr[0],7000));if(imageRequested){Bitmap copy=shot;try{java.io.ByteArrayOutputStream bytes=new java.io.ByteArrayOutputStream();copy.compress(Bitmap.CompressFormat.JPEG,70,bytes);byte[] data=bytes.toByteArray();if(data.length<=2000000){out.put("screenshot_image",Base64.encodeToString(data,Base64.NO_WRAP));out.put("mimeType","image/jpeg");}else out.put("screenshot_image_omitted","too_large");}finally{shot.recycle();}}else shot.recycle();}}else out.put("visual_capture_available",false);return out;}};}
    public static NovaTool schedule(Context context){return new NovaTool(){public String id(){return"task.schedule";}public String description(){return"Schedule a NOVA prompt for a future time. Use epoch milliseconds for triggerAt.";}public JSONObject schema(){try{return new JSONObject().put("type","object").put("required",new JSONArray().put("prompt").put("triggerAt")).put("properties",new JSONObject().put("prompt",new JSONObject().put("type","string")).put("triggerAt",new JSONObject().put("type","integer")).put("repeatEveryMs",new JSONObject().put("type","integer")).put("execute",new JSONObject().put("type","boolean")));}catch(Exception e){return new JSONObject();}}public JSONObject execute(JSONObject input)throws Exception{String p=input==null?"":input.optString("prompt","").trim();long at=input==null?0:input.optLong("triggerAt",0),repeat=input==null?0:input.optLong("repeatEveryMs",0);boolean execute=input!=null&&input.optBoolean("execute",true);if(p.isEmpty())throw new IllegalArgumentException("prompt_required");if(at<=System.currentTimeMillis())throw new IllegalArgumentException("trigger_must_be_in_future");if(repeat!=0&&repeat<60000)throw new IllegalArgumentException("repeat_too_short");String id=NovaProtocol.id();new NovaScheduledTaskStore(context).put(id,p,execute,repeat);NovaScheduler scheduler=new NovaScheduler(context);if(repeat>0)scheduler.repeat(id,at,repeat);else scheduler.schedule(id,at);return new JSONObject().put("scheduled",true).put("taskId",id).put("triggerAt",at).put("repeatEveryMs",repeat);}};}
    public static NovaTool listScheduled(Context context){return new NovaTool(){public String id(){return"task.list";}public String description(){return"List persistent NOVA scheduled tasks.";}public JSONObject schema(){return new JSONObject();}public JSONObject execute(JSONObject input){try{return new JSONObject().put("tasks",new NovaScheduledTaskStore(context).list());}catch(Exception e){return new JSONObject();}}};}
    public static NovaTool cancelScheduled(Context context){return new NovaTool(){public String id(){return"task.cancel_scheduled";}public String description(){return"Cancel a persistent scheduled NOVA task by taskId.";}public JSONObject schema(){try{return new JSONObject().put("type","object").put("required",new JSONArray().put("taskId")).put("properties",new JSONObject().put("taskId",new JSONObject().put("type","string")));}catch(Exception e){return new JSONObject();}}public JSONObject execute(JSONObject input){String id=input==null?"":input.optString("taskId","").trim();if(id.isEmpty())throw new IllegalArgumentException("taskId_required");new NovaScheduler(context).cancel(id);new NovaScheduledTaskStore(context).remove(id);return new JSONObject().put("cancelled",true).put("taskId",id);}};}
    public static NovaTool sendDevice(Context context){return new NovaTool(){public String id(){return"device.send_command";}public String description(){return"Send an action to a connected trusted NOVA node and wait for its verified result.";}public JSONObject schema(){try{return new JSONObject().put("type","object").put("required",new JSONArray().put("nodeId").put("action")).put("properties",new JSONObject().put("nodeId",new JSONObject().put("type","string")).put("action",new JSONObject().put("type","string")).put("value",new JSONObject().put("type","string")));}catch(Exception e){return new JSONObject();}}public JSONObject execute(JSONObject input)throws Exception{String node=input==null?"":input.optString("nodeId","").trim(),action=input==null?"":input.optString("action","").trim(),value=input==null?"":input.optString("value","");if(node.isEmpty()||action.isEmpty())throw new IllegalArgumentException("nodeId_and_action_required");if(value.length()>2048)throw new IllegalArgumentException("value_too_long");NovaRuntime runtime=NovaRuntime.get(context);if(runtime.devices().get(node)==null)throw new IllegalArgumentException("unknown_device");JSONObject result=runtime.sendDeviceCommandAndWait(node,action,value);return new JSONObject().put("sent",true).put("nodeId",node).put("action",action).put("result",result);}};}
    private static JSONObject getJson(String url)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(url).openConnection();c.setConnectTimeout(10000);c.setReadTimeout(15000);c.setRequestProperty("User-Agent","NOVA-AI/1.0");int code=c.getResponseCode();String body=read(code>=200&&code<300?c.getInputStream():c.getErrorStream(),16000);c.disconnect();if(code<200||code>=300)throw new IllegalStateException("search_http_"+code);return new JSONObject(body);}
    private static void addTopics(JSONArray topics,JSONArray out,int max){if(topics==null)return;for(int i=0;i<topics.length()&&out.length()<max;i++){JSONObject t=topics.optJSONObject(i);if(t==null)continue;if(t.has("Topics")){addTopics(t.optJSONArray("Topics"),out,max);continue;}String u=t.optString("FirstURL","");String s=t.optString("Text","");if(!u.isEmpty())out.put(new JSONObject().put("title",s).put("url",u).put("snippet",s));}}
    private static String read(InputStream stream,int max)throws Exception{if(stream==null)return"";StringBuilder out=new StringBuilder();try(BufferedReader r=new BufferedReader(new InputStreamReader(stream,StandardCharsets.UTF_8))){String line;while((line=r.readLine())!=null&&out.length()<max)out.append(line).append('\n');}return out.substring(0,Math.min(out.length(),max));}
    private static String stripHtml(String html){return html.replaceAll("(?is)<script.*?>.*?</script>"," ").replaceAll("(?is)<style.*?>.*?</style>"," ").replaceAll("<[^>]+>"," ").replace("&nbsp;"," ").replace("&amp;","&").replaceAll("\\s+"," ").trim();}
}
